quarkus:
  s3:
    aws:
      credentials:
        type: static
        static-provider:
          access-key-id: test-key
          secret-access-key: test-secret
      region: us-east-1
    endpoint-override: http://localhost:8008
  profile: dev
  log:
    min-level: DEBUG
  http:
    root-path: /document
    # port: 8088
    cors:
      ~: true
      origins: "*"
      methods: OPTIONS, GET, POST, PUT, PATCH, DELETE
      headers: Accept, Content-Type, Content-Length, Accept-Encoding, Authorization
  datasource:
    db-kind: postgresql
    jdbc:
      url: jdbc:postgresql://localhost:5432/document
    username: postgres
    password: password
  hibernate-orm:
    physical-naming-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    log:
      sql: true
      bind-parameters: false
  swagger-ui:
    always-include: true
    urls:
      direct: /document/q/openapi
  # smallrye-openapi:
  #   servers: /master  
  resteasy:
    path: /document 
service:
  name: logistix-document 
bucket:
  name: quarkus.s3.quickstart
  